# Generated by Django 5.1.5 on 2025-02-18 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_status'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='booking.booking'),
        ),
    ]
