# Generated by Django 5.1.5 on 2025-02-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_image_alter_customuser_first_name_and_more'),
        ('accounts', '0003_remove_customuser_username_alter_customuser_groups_and_more'),
    ]

    operations = [
    ]
