# Generated by Django 5.1.5 on 2025-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20250204_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
