# Generated by Django 5.1.5 on 2025-02-06 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
