# Generated by Django 5.1.5 on 2025-02-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='car'),
        ),
        migrations.AddField(
            model_name='car',
            name='licence_plate_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Auto'), ('H', 'Hybrid')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='booking.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.brand'),
        ),
    ]
