# Generated by Django 5.1.5 on 2025-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('C', 'Cancelled'), ('S', 'PAID')], default='P', max_length=1),
        ),
    ]
